---
title: "30 Day Map Challenge"
author: "Iva Brunec"
date: "31 October 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Day 1: Points
A map with points. <br>
Philadelphia base map downloaded from: https://www.pasda.psu.edu/uci/DataSummary.aspx?dataset=7102 <br>
Philadelphia stree tree inventory downloaded from: https://www.opendataphilly.org/dataset/philadelphia-street-tree-inventory 

```{r day 1}
library(sf)
library(ggplot2)
library(dplyr)

phl_base <- read_sf("data/PhiladelphiaStreetCenterlines2020.shp") %>% 
  select(geometry) # only geometry

phl_trees <- st_read("data/69b39f50-460b-4b7b-b5ad-d8d9c491e4392020328-1-1vb911p.sd1c.shp")


ggplot() +
  geom_sf(data = phl_base$geometry, color = 'darkgrey', size = .25) +
  geom_sf(data = phl_trees, size=.05, color='#235347') +
  coord_sf() +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())

```


## Day 2: Lines
A map with lines. <br>
Philadelphia High Injury Network downloaded from: https://www.opendataphilly.org/dataset/high-injury-network <br>
Philadelphia bike network downloaded from: https://www.opendataphilly.org/dataset/bike-network 

```{r day 2}
library(sf)
library(ggplot2)
library(dplyr)

phl_base <- read_sf("data/PhiladelphiaStreetCenterlines2020.shp") %>% 
  select(geometry) # only geometry

phl_hin <- st_read("data/high_injury_network_2020.shp")

phl_bike <- st_read("data/Bike_Network.shp")


ggplot() +
  geom_sf(data = phl_base$geometry, color = 'darkgrey', size = .25, alpha = .3) +
  geom_sf(data = phl_hin, size=.5, color='darkorange2', alpha = .5) +
  geom_sf(data = phl_bike, color = 'cyan4', size = .5, alpha = .5) +
  #coord_sf() +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = 'black'))


```

## Day 3: Polygons
A map with polygons. <br>
Data from: https://www.statista.com/statistics/444589/european-beer-consumption-per-capita-by-country/ and https://en.wikipedia.org/wiki/List_of_countries_by_beer_consumption_per_capita. For wine: https://ourworldindata.org/grapher/wine-consumption-per-person but this contains data from 2014.

```{r day 3}
library(ggplot2)
library(grid)
library(maps)
library(mapdata)
library(ggmap)
library(mapproj)
library(cowplot)
library(dplyr)

world <- map_data("world")


europe_list <- c("Albania","Austria","Belarus","Belgium","Bosnia and Herzegovina","Bulgaria","Croatia","Cyprus",
                   "Czech Republic","Denmark","Estonia","Finland","France",
                   "Germany","Greece","Hungary","Iceland","Ireland","Italy","Latvia", "Kosovo",
                   "Lithuania","Luxembourg","Malta","Moldova","Montenegro", "Netherlands",
                 "Macedonia","Norway","Poland",
                   "Portugal","Romania","Russia","Serbia", "Slovakia","Slovenia","Spain",
                   "Sweden","Switzerland", "Turkey", "UK","Ukraine")

# filter out european countries
europe <- filter(world, region %in% europe_list) 

# read in beer data
beer_data <- read.table("data/europe_beer.csv", header=T, sep=",")

europe$beer_per_capita <- beer_data$beer_per_capita[match(europe$region,beer_data$region)]
europe$wine_per_capita <- beer_data$wine_per_capita[match(europe$region,beer_data$region)]
europe$spirits_per_capita <- beer_data$spirits_per_capita[match(europe$region,beer_data$region)]
europe$group <- as.factor(europe$group)
europe$region <- as.factor(europe$region)

beerplot <- ggplot(data = europe) + 
  geom_polygon(aes(x = long, y = lat, group = group, fill=beer_per_capita), color = 'white', size = .5) + 
  coord_fixed(1.3) +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(), legend.position="bottom",
        legend.key.height = unit(.25, 'cm')) +
  coord_map(xlim = c(-17, 38),  ylim = c(32, 71)) +
  scale_fill_gradient(name = "", low = "#ee9b00", high = "#691e06", na.value = "grey50", limits = c(0,7)) 

wineplot <- ggplot(data = europe) + 
  geom_polygon(aes(x = long, y = lat, group = group, fill=wine_per_capita), color = 'white', size = .5) + 
  coord_fixed(1.3) +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(), legend.position="bottom",
        legend.key.height = unit(.25, 'cm')) +
  coord_map(xlim = c(-17, 38),  ylim = c(32, 71)) +
  scale_fill_gradient(name = "", low = "#d62828", high = "#3f220f", na.value = "grey50", limits = c(0,7)) 

spiritplot <- ggplot(data = europe) + 
  geom_polygon(aes(x = long, y = lat, group = group, fill=spirits_per_capita), color = 'white', size = .5) + 
  coord_fixed(1.3) +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(), legend.position="bottom",
        legend.key.height = unit(.25, 'cm')) +
  coord_map(xlim = c(-17, 38),  ylim = c(32, 71)) +
  scale_fill_gradient(name = "", low = "#63DDDD", high = "#001845", na.value = "grey50", limits = c(0,7)) 



plot_grid(wineplot, beerplot, spiritplot, nrow = 1)



```

