name: Update README with new images

on:
  push:
    paths:
      - "20*/day_*/*"  # Trigger for day folders in any year directory

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set README Path Dynamically
        id: set-readme-path
        run: |
          # Initialize the year variable
          year=""
          
          # Loop through modified files to find the year
          for path in ${{ github.event.head_commit.modified }}; do
            if [[ $path =~ ([0-9]{4}) ]]; then
              year="${BASH_REMATCH[1]}"
              break  # Exit loop after finding the first match
            fi
          done
          
          # Set the README file path based on the year
          if [ -n "$year" ]; then
            README_FILE="$year/README.md"
            echo "README_FILE=$README_FILE" >> $GITHUB_ENV
          else
            echo "Year not found in file path. Exiting."
            exit 1
          fi

      - name: Update README
        if: env.README_FILE  # Only run if README_FILE is set
        run: |
          # Generate header and new entries
          echo "## Daily Challenge Images" > new_content.md
          
          # Loop through each "day_*" folder within the detected year
          for dir in "$year"/day_*; do
            if [ -d "$dir" ]; then
              # Find the PNG image in the directory
              image_path="$dir/$(ls "$dir" | grep .png)"
              # Format day and description from directory name
              day=$(echo "$dir" | cut -d'_' -f 2)
              description=$(echo "$dir" | cut -d'_' -f 3- | tr '_' ' ')
              # Append to new content
              echo "## Day $day: $description" >> new_content.md
              echo "[![alt text]($image_path)]($dir/)" >> new_content.md
              echo "" >> new_content.md
            fi
          done

          # Replace existing README content with new content
          cat new_content.md > $README_FILE

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add $README_FILE
          git commit -m "Update README for $year" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push
